// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Poseidon.Server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Poseidon.Server.Data.Entities.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<int>("EventStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("event_status_id");

                    b.Property<string>("LocationText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location_text");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EventId");

                    b.HasIndex("EventStatusId")
                        .HasDatabaseName("ix_events_status");

                    b.HasIndex("OrganizerId")
                        .HasDatabaseName("ix_events_organizer");

                    b.HasIndex("StartsAt")
                        .HasDatabaseName("ix_events_starts_at");

                    b.HasIndex("StartsAt", "EndsAt")
                        .HasDatabaseName("ix_events_date_range");

                    b.ToTable("events", "public", t =>
                        {
                            t.HasCheckConstraint("ck_events_capacity", "capacity >= 1");

                            t.HasCheckConstraint("ck_events_time", "ends_at > starts_at");
                        });
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.EventStatus", b =>
                {
                    b.Property<int>("EventStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("event_status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status_name");

                    b.HasKey("EventStatusId");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("event_statuses", "public");

                    b.HasData(
                        new
                        {
                            EventStatusId = 1,
                            StatusName = "Draft"
                        },
                        new
                        {
                            EventStatusId = 2,
                            StatusName = "Published"
                        },
                        new
                        {
                            EventStatusId = 3,
                            StatusName = "Cancelled"
                        },
                        new
                        {
                            EventStatusId = 4,
                            StatusName = "Completed"
                        });
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.NotificationDelivery", b =>
                {
                    b.Property<Guid>("NotificationDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_delivery_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("channel");

                    b.Property<Guid>("NotificationJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_job_id");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("NotificationDeliveryId");

                    b.HasIndex("NotificationJobId")
                        .IsUnique()
                        .HasDatabaseName("ux_notification_deliveries_job_success")
                        .HasFilter("result = 'Succeeded'");

                    b.HasIndex("RecipientUserId")
                        .HasDatabaseName("ix_notification_deliveries_recipient");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("ix_notification_deliveries_sent_at");

                    b.ToTable("notification_deliveries", "public", t =>
                        {
                            t.HasCheckConstraint("ck_notification_deliveries_channel", "channel IN ('Email')");

                            t.HasCheckConstraint("ck_notification_deliveries_result", "result IN ('Succeeded', 'Failed')");
                        });
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.NotificationJob", b =>
                {
                    b.Property<Guid>("NotificationJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_job_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Email")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("JobStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("job_status_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset?>("PublisherLockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publisher_locked_until");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("NotificationJobId");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_notification_jobs_event");

                    b.HasIndex("Payload")
                        .HasDatabaseName("ix_notification_jobs_payload");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Payload"), "gin");

                    b.HasIndex("RecipientUserId")
                        .HasDatabaseName("ix_notification_jobs_recipient");

                    b.HasIndex("JobStatusId", "AvailableAt")
                        .HasDatabaseName("ix_notification_jobs_status_available");

                    b.HasIndex("JobStatusId", "AvailableAt", "PublisherLockedUntil")
                        .HasDatabaseName("ix_notification_jobs_publishable")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("notification_jobs", "public", t =>
                        {
                            t.HasCheckConstraint("ck_notification_jobs_attempts", "attempts >= 0");

                            t.HasCheckConstraint("ck_notification_jobs_channel", "channel IN ('Email')");
                        });
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.NotificationJobStatus", b =>
                {
                    b.Property<int>("JobStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("job_status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status_name");

                    b.HasKey("JobStatusId");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("notification_job_statuses", "public");

                    b.HasData(
                        new
                        {
                            JobStatusId = 1,
                            StatusName = "Pending"
                        },
                        new
                        {
                            JobStatusId = 2,
                            StatusName = "Processing"
                        },
                        new
                        {
                            JobStatusId = 3,
                            StatusName = "Succeeded"
                        },
                        new
                        {
                            JobStatusId = 4,
                            StatusName = "Failed"
                        });
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.Registration", b =>
                {
                    b.Property<Guid>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RegistrationStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("registration_status_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("RegistrationId");

                    b.HasIndex("RegistrationStatusId");

                    b.HasIndex("StudentId");

                    b.HasIndex("EventId", "RegistrationStatusId")
                        .HasDatabaseName("ix_registrations_confirmed")
                        .HasFilter("cancelled_at IS NULL");

                    b.HasIndex("EventId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ux_registrations_one_active")
                        .HasFilter("cancelled_at IS NULL");

                    b.HasIndex("EventId", "RegistrationStatusId", "RegisteredAt")
                        .HasDatabaseName("ix_registrations_waitlist_order");

                    b.ToTable("registrations", "public");
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.RegistrationStatus", b =>
                {
                    b.Property<int>("RegistrationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("registration_status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistrationStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status_name");

                    b.HasKey("RegistrationStatusId");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("registration_statuses", "public");

                    b.HasData(
                        new
                        {
                            RegistrationStatusId = 1,
                            StatusName = "Confirmed"
                        },
                        new
                        {
                            RegistrationStatusId = 2,
                            StatusName = "Waitlisted"
                        },
                        new
                        {
                            RegistrationStatusId = 3,
                            StatusName = "Cancelled"
                        });
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("user_roles", "public");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Student"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Teacher"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.Event", b =>
                {
                    b.HasOne("Poseidon.Server.Data.Entities.EventStatus", "EventStatus")
                        .WithMany("Events")
                        .HasForeignKey("EventStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Poseidon.Server.Data.Entities.User", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventStatus");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.NotificationDelivery", b =>
                {
                    b.HasOne("Poseidon.Server.Data.Entities.NotificationJob", "NotificationJob")
                        .WithMany()
                        .HasForeignKey("NotificationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poseidon.Server.Data.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotificationJob");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.NotificationJob", b =>
                {
                    b.HasOne("Poseidon.Server.Data.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poseidon.Server.Data.Entities.NotificationJobStatus", "JobStatus")
                        .WithMany("NotificationJobs")
                        .HasForeignKey("JobStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Poseidon.Server.Data.Entities.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("JobStatus");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.Registration", b =>
                {
                    b.HasOne("Poseidon.Server.Data.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Poseidon.Server.Data.Entities.RegistrationStatus", "RegistrationStatus")
                        .WithMany("Registrations")
                        .HasForeignKey("RegistrationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Poseidon.Server.Data.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("RegistrationStatus");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.User", b =>
                {
                    b.HasOne("Poseidon.Server.Data.Entities.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.EventStatus", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.NotificationJobStatus", b =>
                {
                    b.Navigation("NotificationJobs");
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.RegistrationStatus", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Poseidon.Server.Data.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
