CREATE TABLE event_statuses (
    event_status_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE registration_statuses (
    registration_status_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE notification_job_statuses (
    job_status_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE user_roles (
    role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(30) NOT NULL UNIQUE
);

INSERT INTO event_statuses (event_status_id, status_name) VALUES
    (1, 'Draft'),
    (2, 'Published'),
    (3, 'Cancelled'),
    (4, 'Completed');

INSERT INTO registration_statuses (registration_status_id, status_name) VALUES
    (1, 'Confirmed'),
    (2, 'Waitlisted'),
    (3, 'Cancelled');

INSERT INTO notification_job_statuses (job_status_id, status_name) VALUES
    (1, 'Pending'),
    (2, 'Processing'),
    (3, 'Succeeded'),
    (4, 'Failed');

INSERT INTO user_roles (role_id, role_name) VALUES
    (1, 'Student'),
    (2, 'Teacher'),
    (3, 'Admin');

CREATE TABLE users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    role_id INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id) REFERENCES user_roles(role_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX ux_users_email_lower
ON users (lower(email));

CREATE TABLE events (
    event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organizer_id UUID NOT NULL,
    event_status_id INT NOT NULL,
    title VARCHAR(150) NOT NULL,
    description TEXT,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    capacity INT NOT NULL,
    location_text VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ,

    CONSTRAINT ck_events_capacity CHECK (capacity >= 1),
    CONSTRAINT ck_events_time CHECK (ends_at > starts_at),

    CONSTRAINT fk_events_organizer
        FOREIGN KEY (organizer_id) REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_events_status
        FOREIGN KEY (event_status_id) REFERENCES event_statuses(event_status_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE TABLE registrations (
    registration_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id UUID NOT NULL,
    student_id UUID NOT NULL,
    registration_status_id INT NOT NULL,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at TIMESTAMPTZ,

    CONSTRAINT fk_registrations_event
        FOREIGN KEY (event_id) REFERENCES events(event_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_registrations_student
        FOREIGN KEY (student_id) REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_registrations_status
        FOREIGN KEY (registration_status_id)
        REFERENCES registration_statuses(registration_status_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX ux_registrations_one_active
ON registrations(event_id, student_id)
WHERE cancelled_at IS NULL;

CREATE INDEX ix_registrations_waitlist_order
ON registrations(event_id, registration_status_id, registered_at);

CREATE INDEX ix_registrations_confirmed
ON registrations(event_id, registration_status_id)
WHERE cancelled_at IS NULL;

CREATE TABLE notification_jobs (
    notification_job_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    event_id UUID NOT NULL,
    recipient_user_id UUID NOT NULL,

    job_status_id INT NOT NULL,
    payload JSONB NOT NULL,

    title VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    channel VARCHAR(30) NOT NULL DEFAULT 'Email',

    attempts INT NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,
    last_error TEXT,

    CONSTRAINT ck_notification_jobs_attempts CHECK (attempts >= 0),
    CONSTRAINT ck_notification_jobs_channel CHECK (
        channel IN ('Email')
    ),

    CONSTRAINT fk_notification_jobs_event
        FOREIGN KEY (event_id) REFERENCES events(event_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_notification_jobs_recipient
        FOREIGN KEY (recipient_user_id) REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_notification_jobs_status
        FOREIGN KEY (job_status_id)
        REFERENCES notification_job_statuses(job_status_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE TABLE notification_deliveries (
    notification_delivery_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    notification_job_id UUID NOT NULL,
    recipient_user_id UUID NOT NULL,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    channel VARCHAR(30) NOT NULL,
    result VARCHAR(50) NOT NULL,

    CONSTRAINT ck_notification_deliveries_channel CHECK (
        channel IN ('Email')
    ),
    CONSTRAINT ck_notification_deliveries_result CHECK (
        result IN ('Succeeded', 'Failed')
    ),

    CONSTRAINT fk_notification_deliveries_job
        FOREIGN KEY (notification_job_id)
        REFERENCES notification_jobs(notification_job_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_notification_deliveries_recipient
        FOREIGN KEY (recipient_user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_events_set_updated_at
BEFORE UPDATE ON events
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();


CREATE INDEX ix_users_role
ON users(role_id);

CREATE INDEX ix_events_organizer
ON events(organizer_id);

CREATE INDEX ix_events_status
ON events(event_status_id);

CREATE INDEX ix_events_starts_at
ON events(starts_at);

CREATE INDEX ix_events_date_range
ON events(starts_at, ends_at);

CREATE INDEX ix_notification_jobs_event
ON notification_jobs(event_id);

CREATE INDEX ix_notification_jobs_recipient
ON notification_jobs(recipient_user_id);

CREATE INDEX ix_notification_jobs_status_available
ON notification_jobs(job_status_id, available_at);

CREATE INDEX ix_notification_jobs_payload
ON notification_jobs USING GIN (payload);

CREATE INDEX ix_notification_deliveries_job
ON notification_deliveries(notification_job_id);

CREATE INDEX ix_notification_deliveries_recipient
ON notification_deliveries(recipient_user_id);

CREATE INDEX ix_notification_deliveries_sent_at
ON notification_deliveries(sent_at);
