CREATE TABLE IF NOT EXISTS notification_job_statuses (
    job_status_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR(30) NOT NULL UNIQUE
);

INSERT INTO notification_job_statuses (job_status_id, status_name) VALUES
    (1, 'Pending'),
    (2, 'Processing'),
    (3, 'Succeeded'),
    (4, 'Failed')
ON CONFLICT (job_status_id) DO UPDATE
SET status_name = EXCLUDED.status_name;

CREATE TABLE IF NOT EXISTS notification_jobs (
    notification_job_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id UUID NOT NULL,
    recipient_user_id UUID NOT NULL,
    job_status_id INT NOT NULL,
    payload JSONB NOT NULL,
    title VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    channel VARCHAR(30) NOT NULL DEFAULT 'Email',
    attempts INT NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    publisher_locked_until TIMESTAMPTZ,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,
    last_error TEXT,
    CONSTRAINT ck_notification_jobs_attempts CHECK (attempts >= 0),
    CONSTRAINT ck_notification_jobs_channel CHECK (channel IN ('Email')),
    CONSTRAINT fk_notification_jobs_event
        FOREIGN KEY (event_id) REFERENCES events(event_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_notification_jobs_recipient
        FOREIGN KEY (recipient_user_id) REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_notification_jobs_status
        FOREIGN KEY (job_status_id)
        REFERENCES notification_job_statuses(job_status_id)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS notification_deliveries (
    notification_delivery_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    notification_job_id UUID NOT NULL,
    recipient_user_id UUID NOT NULL,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    channel VARCHAR(30) NOT NULL,
    result VARCHAR(50) NOT NULL,
    CONSTRAINT ck_notification_deliveries_channel CHECK (channel IN ('Email')),
    CONSTRAINT ck_notification_deliveries_result CHECK (result IN ('Succeeded', 'Failed')),
    CONSTRAINT fk_notification_deliveries_job
        FOREIGN KEY (notification_job_id)
        REFERENCES notification_jobs(notification_job_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_notification_deliveries_recipient
        FOREIGN KEY (recipient_user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_notification_jobs_event
ON notification_jobs(event_id);

CREATE INDEX IF NOT EXISTS ix_notification_jobs_recipient
ON notification_jobs(recipient_user_id);

CREATE INDEX IF NOT EXISTS ix_notification_jobs_status_available
ON notification_jobs(job_status_id, available_at);

CREATE INDEX IF NOT EXISTS ix_notification_jobs_publishable
ON notification_jobs(job_status_id, available_at, publisher_locked_until)
WHERE published_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_notification_jobs_payload
ON notification_jobs USING GIN (payload);

CREATE INDEX IF NOT EXISTS ix_notification_deliveries_job
ON notification_deliveries(notification_job_id);

CREATE INDEX IF NOT EXISTS ix_notification_deliveries_recipient
ON notification_deliveries(recipient_user_id);

CREATE INDEX IF NOT EXISTS ix_notification_deliveries_sent_at
ON notification_deliveries(sent_at);

CREATE UNIQUE INDEX IF NOT EXISTS ux_notification_deliveries_job_success
ON notification_deliveries(notification_job_id)
WHERE result = 'Succeeded';
