CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE TABLE public.event_statuses (
        event_status_id integer GENERATED BY DEFAULT AS IDENTITY,
        status_name character varying(30) NOT NULL,
        CONSTRAINT "PK_event_statuses" PRIMARY KEY (event_status_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE TABLE public.notification_job_statuses (
        job_status_id integer GENERATED BY DEFAULT AS IDENTITY,
        status_name character varying(30) NOT NULL,
        CONSTRAINT "PK_notification_job_statuses" PRIMARY KEY (job_status_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE TABLE public.registration_statuses (
        registration_status_id integer GENERATED BY DEFAULT AS IDENTITY,
        status_name character varying(30) NOT NULL,
        CONSTRAINT "PK_registration_statuses" PRIMARY KEY (registration_status_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE TABLE public.user_roles (
        role_id integer GENERATED BY DEFAULT AS IDENTITY,
        role_name character varying(30) NOT NULL,
        CONSTRAINT "PK_user_roles" PRIMARY KEY (role_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE TABLE public.users (
        user_id uuid NOT NULL DEFAULT (gen_random_uuid()),
        email character varying(255) NOT NULL,
        password_hash character varying(255) NOT NULL,
        display_name character varying(100) NOT NULL,
        role_id integer NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        CONSTRAINT "PK_users" PRIMARY KEY (user_id),
        CONSTRAINT "FK_users_user_roles_role_id" FOREIGN KEY (role_id) REFERENCES public.user_roles (role_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE TABLE public.events (
        event_id uuid NOT NULL DEFAULT (gen_random_uuid()),
        organizer_id uuid NOT NULL,
        event_status_id integer NOT NULL DEFAULT 1,
        title character varying(150) NOT NULL,
        description text,
        starts_at timestamp with time zone NOT NULL,
        ends_at timestamp with time zone NOT NULL,
        capacity integer NOT NULL,
        location_text character varying(255),
        created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        updated_at timestamp with time zone,
        CONSTRAINT "PK_events" PRIMARY KEY (event_id),
        CONSTRAINT ck_events_capacity CHECK (capacity >= 1),
        CONSTRAINT ck_events_time CHECK (ends_at > starts_at),
        CONSTRAINT "FK_events_event_statuses_event_status_id" FOREIGN KEY (event_status_id) REFERENCES public.event_statuses (event_status_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_events_users_organizer_id" FOREIGN KEY (organizer_id) REFERENCES public.users (user_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE TABLE public.notification_jobs (
        notification_job_id uuid NOT NULL DEFAULT (gen_random_uuid()),
        event_id uuid NOT NULL,
        recipient_user_id uuid NOT NULL,
        job_status_id integer NOT NULL,
        payload jsonb NOT NULL,
        title character varying(150) NOT NULL,
        message text NOT NULL,
        channel character varying(30) NOT NULL DEFAULT 'Email',
        attempts integer NOT NULL DEFAULT 0,
        available_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        publisher_locked_until timestamp with time zone,
        published_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        processed_at timestamp with time zone,
        last_error text,
        CONSTRAINT "PK_notification_jobs" PRIMARY KEY (notification_job_id),
        CONSTRAINT ck_notification_jobs_attempts CHECK (attempts >= 0),
        CONSTRAINT ck_notification_jobs_channel CHECK (channel IN ('Email')),
        CONSTRAINT "FK_notification_jobs_events_event_id" FOREIGN KEY (event_id) REFERENCES public.events (event_id) ON DELETE CASCADE,
        CONSTRAINT "FK_notification_jobs_notification_job_statuses_job_status_id" FOREIGN KEY (job_status_id) REFERENCES public.notification_job_statuses (job_status_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_notification_jobs_users_recipient_user_id" FOREIGN KEY (recipient_user_id) REFERENCES public.users (user_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE TABLE public.registrations (
        registration_id uuid NOT NULL DEFAULT (gen_random_uuid()),
        event_id uuid NOT NULL,
        student_id uuid NOT NULL,
        registration_status_id integer NOT NULL,
        registered_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        cancelled_at timestamp with time zone,
        CONSTRAINT "PK_registrations" PRIMARY KEY (registration_id),
        CONSTRAINT "FK_registrations_events_event_id" FOREIGN KEY (event_id) REFERENCES public.events (event_id) ON DELETE CASCADE,
        CONSTRAINT "FK_registrations_registration_statuses_registration_status_id" FOREIGN KEY (registration_status_id) REFERENCES public.registration_statuses (registration_status_id) ON DELETE RESTRICT,
        CONSTRAINT "FK_registrations_users_student_id" FOREIGN KEY (student_id) REFERENCES public.users (user_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE TABLE public.notification_deliveries (
        notification_delivery_id uuid NOT NULL DEFAULT (gen_random_uuid()),
        notification_job_id uuid NOT NULL,
        recipient_user_id uuid NOT NULL,
        sent_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        channel character varying(30) NOT NULL,
        result character varying(50) NOT NULL,
        CONSTRAINT "PK_notification_deliveries" PRIMARY KEY (notification_delivery_id),
        CONSTRAINT ck_notification_deliveries_channel CHECK (channel IN ('Email')),
        CONSTRAINT ck_notification_deliveries_result CHECK (result IN ('Succeeded', 'Failed')),
        CONSTRAINT "FK_notification_deliveries_notification_jobs_notification_job_~" FOREIGN KEY (notification_job_id) REFERENCES public.notification_jobs (notification_job_id) ON DELETE CASCADE,
        CONSTRAINT "FK_notification_deliveries_users_recipient_user_id" FOREIGN KEY (recipient_user_id) REFERENCES public.users (user_id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    INSERT INTO public.event_statuses (event_status_id, status_name)
    VALUES (1, 'Draft');
    INSERT INTO public.event_statuses (event_status_id, status_name)
    VALUES (2, 'Published');
    INSERT INTO public.event_statuses (event_status_id, status_name)
    VALUES (3, 'Cancelled');
    INSERT INTO public.event_statuses (event_status_id, status_name)
    VALUES (4, 'Completed');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    INSERT INTO public.notification_job_statuses (job_status_id, status_name)
    VALUES (1, 'Pending');
    INSERT INTO public.notification_job_statuses (job_status_id, status_name)
    VALUES (2, 'Processing');
    INSERT INTO public.notification_job_statuses (job_status_id, status_name)
    VALUES (3, 'Succeeded');
    INSERT INTO public.notification_job_statuses (job_status_id, status_name)
    VALUES (4, 'Failed');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    INSERT INTO public.registration_statuses (registration_status_id, status_name)
    VALUES (1, 'Confirmed');
    INSERT INTO public.registration_statuses (registration_status_id, status_name)
    VALUES (2, 'Waitlisted');
    INSERT INTO public.registration_statuses (registration_status_id, status_name)
    VALUES (3, 'Cancelled');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    INSERT INTO public.user_roles (role_id, role_name)
    VALUES (1, 'Student');
    INSERT INTO public.user_roles (role_id, role_name)
    VALUES (2, 'Teacher');
    INSERT INTO public.user_roles (role_id, role_name)
    VALUES (3, 'Admin');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_event_statuses_status_name" ON public.event_statuses (status_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX ix_events_date_range ON public.events (starts_at, ends_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX ix_events_organizer ON public.events (organizer_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX ix_events_starts_at ON public.events (starts_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX ix_events_status ON public.events (event_status_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX ix_notification_deliveries_recipient ON public.notification_deliveries (recipient_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX ix_notification_deliveries_sent_at ON public.notification_deliveries (sent_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE UNIQUE INDEX ux_notification_deliveries_job_success ON public.notification_deliveries (notification_job_id) WHERE result = 'Succeeded';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_notification_job_statuses_status_name" ON public.notification_job_statuses (status_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX ix_notification_jobs_event ON public.notification_jobs (event_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX ix_notification_jobs_payload ON public.notification_jobs USING gin (payload);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX ix_notification_jobs_publishable ON public.notification_jobs (job_status_id, available_at, publisher_locked_until) WHERE published_at IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX ix_notification_jobs_recipient ON public.notification_jobs (recipient_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX ix_notification_jobs_status_available ON public.notification_jobs (job_status_id, available_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_registration_statuses_status_name" ON public.registration_statuses (status_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX ix_registrations_confirmed ON public.registrations (event_id, registration_status_id) WHERE cancelled_at IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX "IX_registrations_registration_status_id" ON public.registrations (registration_status_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX "IX_registrations_student_id" ON public.registrations (student_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX ix_registrations_waitlist_order ON public.registrations (event_id, registration_status_id, registered_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE UNIQUE INDEX ux_registrations_one_active ON public.registrations (event_id, student_id) WHERE cancelled_at IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_user_roles_role_name" ON public.user_roles (role_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE INDEX ix_users_role ON public.users (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE UNIQUE INDEX ux_users_email ON public.users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    CREATE FUNCTION public.set_updated_at()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
    BEGIN
        NEW.updated_at = CURRENT_TIMESTAMP;
        RETURN NEW;
    END;
    $$;

    CREATE TRIGGER trg_events_set_updated_at
    BEFORE UPDATE ON public.events
    FOR EACH ROW
    EXECUTE FUNCTION public.set_updated_at();
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('public.event_statuses', 'event_status_id'),
        GREATEST(
            (SELECT MAX(event_status_id) FROM public.event_statuses) + 1,
            nextval(pg_get_serial_sequence('public.event_statuses', 'event_status_id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('public.notification_job_statuses', 'job_status_id'),
        GREATEST(
            (SELECT MAX(job_status_id) FROM public.notification_job_statuses) + 1,
            nextval(pg_get_serial_sequence('public.notification_job_statuses', 'job_status_id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('public.registration_statuses', 'registration_status_id'),
        GREATEST(
            (SELECT MAX(registration_status_id) FROM public.registration_statuses) + 1,
            nextval(pg_get_serial_sequence('public.registration_statuses', 'registration_status_id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('public.user_roles', 'role_id'),
        GREATEST(
            (SELECT MAX(role_id) FROM public.user_roles) + 1,
            nextval(pg_get_serial_sequence('public.user_roles', 'role_id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260701161458_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260701161458_InitialCreate', '9.0.0');
    END IF;
END $EF$;
COMMIT;

